<?php

function alan_test_menu() {
  $items['islandora/mads/build'] = array(
    'page callback' => 'build_all_mads',
    'type' => MENU_CALLBACK,
    'access callback' => 'user_access',
    'access arguments' => array('ISLANDORA_CRITICAL_EDITION_ADVANCED_READ'),
  );
  return $items;
}

function build_all_mads($path) {
  $scholars = read_csv($path);
  foreach ($scholars as $scholar) {
    build_mads($scholar);
  }
}

function read_csv($path) {
  ini_set("auto_detect_line_endings", "1");
  $scolars = array();
  if (($handle = fopen($path, "r")) !== FALSE) {
    while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
      if (!isset($header)) {
        $header = $data;
        continue;
      }
      for ($counter = 0; $counter < count($data); $counter++) {
        $scholar[$header[$counter]] = $data[$counter];
      }
      $scholars[] = $scholar;
    }
    fclose($handle);
  }
  return $scholars;
}

function build_mads($scholar) {
  if (isset($scholar['SCHOLAR_NAME'])) {
    $name['name'] = $scholar['SCHOLAR_NAME'];
    if (isset($scholar['SCHOLAR_DATE'])) {
      $name['date'] = $scholar['SCHOLAR_DATE'];
    }
  }
  $address_fields = array(
    'STREET1',
    'STREET2',
    'CITY',
    'PROVINCE',
    'STATE',
    'COUNTRY',
    'POSTAL_CODE',
  );



  $xml = new DomDocument('1.0', 'UTF-8');
  $xml->preserveWhiteSpace = false;
  $xml->formatOutput = true;
  $mads_uri = "http://www.loc.gov/mads/v2";
  //root.
  $root = $xml->createElementNS($mads_uri, 'mads:mads');
  $xml->appendChild($root);
  if (isset($name)) {
    add_authority($xml, 'authority', $name);
  }
  $address = array();
  foreach ($address_fields as $field) {
    if (isset($scholar[$field])) {
      $address[$field] = $scholar[$field];
    }
  }
  if (count($address) > 0) {
    add_address($xml, $address);
  }
  if (isset($scholar['AFFILIATION'])) {
    $affiliation['position'] = $scholar['AFFILIATION'];
    if (isset($scholar['AFFILIATION_START']) && $scholar['AFFILIATION_START'] != '') {
      $affiliation['start'] = $scholar['AFFILIATION_START'];
    }
    if (isset($scholar['AFFILIATION_END']) && $scholar['AFFILIATION_END'] != '') {
      $affiliation['end'] = $scholar['AFFILIATION_END'];
    }
    add_affiliation($xml, $affiliation);
  }
  print $xml->savexml();
}

function add_authority($xml, $type, $name) {
  $mads_uri = "http://www.loc.gov/mads/v2";
  $root = $xml->documentElement;
  // authority.
  $authority = $xml->createElementNS($mads_uri, "mads:$type");
  $authority->setAttribute('geographicSubdivision', "not applicable");
  $root->appendChild($authority);
  // name.
  $name_node = $xml->createElementNS($mads_uri, 'mads:name');
  $name_node->setAttribute('type', 'personal');
  $authority->appendChild($name_node);
  //namePart
  $name_part = $xml->createElementNS($mads_uri, 'mads:namePart', $name['name']);
  $name_node->appendChild($name_part);
  // date
  if (isset($name['date'])) {
    $name_date = $xml->createElementNS($mads_uri, 'mads:namePart', $name['date']);
    $name_date->setAttribute('type', 'date');
    $name_node->appendChild($name_date);
  }
}

function add_address($xml, $address_values) {
  $mads_uri = "http://www.loc.gov/mads/v2";
  $root = $xml->documentElement;
  $affiliation = $xml->createElementNS($mads_uri, "mads:affiliation");
  $root->appendChild($affiliation);
  $address = $xml->createElementNS($mads_uri, "mads:address");
  $affiliation->appendChild($address);
  foreach ($address_values as $key => $value) {
    $line = $xml->createElementNS($mads_uri, "mads:$key", $value);
    $address->appendChild($line);
  }
}

function add_affiliation($xml, $affiliation_values) {
  if (!isset($affiliation_values['position'])) {
    return;
  }
  $mads_uri = "http://www.loc.gov/mads/v2";
  $root = $xml->documentElement;
  $affiliation = $xml->createElementNS($mads_uri, "mads:affiliation");
  $root->appendChild($affiliation);
  $position = $xml->createElementNS($mads_uri, "mads:position", $affiliation_values['position']);
  $affiliation->appendChild($position);
  $points = array('start', 'end');
  foreach ($points as $point) {
    if (isset($affiliation_values[$point])) {
      $line = $xml->createElementNS($mads_uri, "mads:dateValid", $affiliation_values[$point]);
      $line->setAttribute('point', $point);
      $affiliation->appendChild($line);
    }
  }
}

function alan_test_call() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  $module = "islandora_audio";
  if (module_exists($module)) {
    $info = islandora_solution_packs_get_required_objects($module);
    $objects_to_add = array();
    foreach ($info['objects'] as $key => $candidate) {
      $models = $candidate->models;
      if (in_array('fedora-system:ContentModel-3.0', $candidate->models)) {
        $objects_to_add[] = $candidate;
      }
    }
    if (count($objects_to_add) > 0) {
      foreach ($objects_to_add as $object_to_add) {
        $old_object = islandora_object_load($object_to_add->id);
        if ($old_object) {
          $deleted = islandora_delete_object($old_object);
          if (!$deleted) {

            continue;
          }
        }
        $new_object = islandora_add_object($object_to_add);
        $verb = $deleted ? dt("Replaced") : dt("Added");
        if ($new_object) {
          drush_log("$verb " . $object_to_add->id . " - " . $object_to_add->label);
        }
      }
    }
  }
}

/**
 * Implements hook_CMODEL_PID_islandora_solr_object_result_alter().
 */
function alan_test_pack_packersplus_assembly_islandora_solr_object_result_alter(&$search_results, $query_processor) {
  module_load_include('inc', 'packers_solution_pack', 'packers_solution_pack');
  //$filter = packers_solution_pack_parse_contextual_filter_from_pid($search_results['solr_doc']['PID']);
  if (isset($search_results['solr_doc']['RELS_EXT_has_serial_number_of_literal_ms']) && !empty($search_results['solr_doc']['RELS_EXT_has_serial_number_of_literal_ms'][0])) {
    $search_results['object_url'] = 'assembly-serial-view/' . $filter;
  }
  else {
    $search_results['object_url'] = 'assembly-purchase-order-view/' . $filter;
  }
}