<?php

function alan_test_menu() {
  $items['islandora/emic/collection'] = array(
    'page callback' => 'build_MADS',
    'type' => MENU_CALLBACK,
    'access callback' => 'user_access',
    'access arguments' => array(ISLANDORA_CRITICAL_EDITION_ADVANCED_READ),
  );
  return $items;
}

function build_all_mads($path) {
  $scholars = read_csv($path);
  foreach ($scholars as $scholar) {
    build_mads($scholar);
  }
}

function read_csv($path) {
  ini_set("auto_detect_line_endings", "1");
  $scolars = array();
  if (($handle = fopen($path, "r")) !== FALSE) {
    while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
      if (!isset($header)) {
        $header = $data;
        continue;
      }
      for ($counter = 0; $counter < count($data); $counter++) {
        $scholar[$header[$counter]] = $data[$counter];
      }
      $scholars[] = $scholar;
    }
    fclose($handle);
  }
  return $scholars;
}

function build_mads($scholar) {
  if (isset($scholar['SCHOLAR_NAME'])) {
    $name['name'] = $scholar['SCHOLAR_NAME'];
    if (isset($scholar['SCHOLAR_DATE'])) {
      $name['date'] = $scholar['SCHOLAR_DATE'];
    }
  }
  $address_fields = array(
    'STREET1',
    'STREET2',
    'CITY',
    'PROVINCE',
    'STATE',
    'COUNTRY',
    'POSTAL_CODE',
  );



  $xml = new DomDocument('1.0', 'UTF-8');
  $xml->preserveWhiteSpace = false;
  $xml->formatOutput = true;
  $mads_uri = "http://www.loc.gov/mads/v2";
  //root.
  $root = $xml->createElementNS($mads_uri, 'mads:mads');
  $xml->appendChild($root);
  if (isset($name)) {
    add_authority($xml, 'authority', $name);
  }
  $address = array();
  foreach ($address_fields as $field) {
    if (isset($scholar[$field])) {
      $address[$field] = $scholar[$field];
    }
  }
  if (count($address) > 0) {
    add_address($xml, $address);
  }
  if (isset($scholar['AFFILIATION'])) {
    $affiliation['position'] = $scholar['AFFILIATION'];
    if (isset($scholar['AFFILIATION_START']) && $scholar['AFFILIATION_START'] != '') {
      $affiliation['start'] = $scholar['AFFILIATION_START'];
    }
    if (isset($scholar['AFFILIATION_END']) && $scholar['AFFILIATION_END'] != '') {
      $affiliation['end'] = $scholar['AFFILIATION_END'];
    }
    add_affiliation($xml, $affiliation);
  }
  print $xml->savexml();
}

function add_authority($xml, $type, $name) {
  $mads_uri = "http://www.loc.gov/mads/v2";
  $root = $xml->documentElement;
  // authority.
  $authority = $xml->createElementNS($mads_uri, "mads:$type");
  $authority->setAttribute('geographicSubdivision', "not applicable");
  $root->appendChild($authority);
  // name.
  $name_node = $xml->createElementNS($mads_uri, 'mads:name');
  $name_node->setAttribute('type', 'personal');
  $authority->appendChild($name_node);
  //namePart
  $name_part = $xml->createElementNS($mads_uri, 'mads:namePart', $name['name']);
  $name_node->appendChild($name_part);
  // date
  if (isset($name['date'])) {
    $name_date = $xml->createElementNS($mads_uri, 'mads:namePart', $name['date']);
    $name_date->setAttribute('type', 'date');
    $name_node->appendChild($name_date);
  }
}

function add_address($xml, $address_values) {
  $mads_uri = "http://www.loc.gov/mads/v2";
  $root = $xml->documentElement;
  $affiliation = $xml->createElementNS($mads_uri, "mads:affiliation");
  $root->appendChild($affiliation);
  $address = $xml->createElementNS($mads_uri, "mads:address");
  $affiliation->appendChild($address);
  foreach ($address_values as $key => $value) {
    $line = $xml->createElementNS($mads_uri, "mads:$key", $value);
    $address->appendChild($line);
  }
}

function add_affiliation($xml, $affiliation_values) {
  if (!isset($affiliation_values['position'])) {
    return;
  }
  $mads_uri = "http://www.loc.gov/mads/v2";
  $root = $xml->documentElement;
  $affiliation = $xml->createElementNS($mads_uri, "mads:affiliation");
  $root->appendChild($affiliation);
  $position = $xml->createElementNS($mads_uri, "mads:position", $affiliation_values['position']);
  $affiliation->appendChild($position);
  $points = array('start', 'end');
  foreach ($points as $point) {
    if (isset($affiliation_values[$point])) {
      $line = $xml->createElementNS($mads_uri, "mads:dateValid", $affiliation_values[$point]);
      $line->setAttribute('point', $point);
      $affiliation->appendChild($line);
    }
  }
}